default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: homey_development
  # Optional: You can specify a username and password if needed for local dev.
  # username: homey
  # password: <%= ENV['HOMEY_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: homey_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5