default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: homey_development
  # Optional: You can specify a username and password if needed for local dev.
  # username: homey
  # password: <%= ENV['HOMEY_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: homey_test

production:
  primary:
    <<: *default
    database: homey_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
  cable:
    <<: *default
    database: homey_cable_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>